version: '3'

env:
  TERRAFORM_dir: '{{.TERRAFORM_DIR}}'

tasks:
  cz-commit:
    desc: Create a commit using Commitizen (Conventional Commits standard)
    cmds:
      - cz commit

  cz-check:
    desc: Check if commit messages follow Conventional Commits
    cmds:
      - cz check

  cz-bump:
    desc: Bump version, tag, and update changelog using Commitizen
    cmds:
      - cz bump

  release:
    desc: Bump version and push tags (run after merge to main)
    cmds:
      - cz bump
      - git push --follow-tags

  tf-init:
    desc: Initialize Terraform in terraform directory
    dir: '{{.TERRAFORM_DIR}}'
    cmds:
      - terraform init

  tf-validate:
    desc: Validate Terraform configuration
    dir: '{{.TERRAFORM_DIR}}'
    cmds:
      - terraform validate

  tf-plan:
    desc: Show the execution plan
    dir: '{{.TERRAFORM_DIR}}'
    cmds:
      - terraform plan

  tf-apply:
    desc: Apply infrastructure changes
    dir: '{{.TERRAFORM_DIR}}'
    cmds:
      - terraform apply

  tf-destroy:
    desc: Destroy all managed infrastructure
    dir: '{{.TERRAFORM_DIR}}'
    cmds:
      - terraform destroy

  tf-fmt:
    desc: Format Terraform files
    dir: '{{.TERRAFORM_DIR}}'
    cmds:
      - terraform fmt -recursive

  tf-all:
    desc: Run fmt → init → validate → plan (common workflow)
    cmds:
      - task: tf-fmt
      - task: tf-init
      - task: tf-validate
      - task: tf-plan
